#!/bin/bash

csv_file=$1

awk -vOFS=, '{print NR,$0}' $csv_file | fzf --height=100% --border=sharp \
--preview='cat '$csv_file' | csv-record $(echo {} | cut -d, -f1)' \
--preview-window='45%,border-sharp' \
--prompt='Lines > ' \
--bind='ctrl-p:toggle-preview'
